substitutions:
  name: balcony-sensors
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_status_led: GPIO02
  pin_light_output: GPIO05
  pin_dht: GPIO16
  pin_remote_receiver: GPIO14

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [base.yaml, status/led.yaml, sensors/dht.yaml]
    refresh: 10 min

esp8266:
  board: d1_mini

output:
  - platform: esp8266_pwm
    id: light_output
    pin: $pin_light_output

light:
  - platform: monochromatic
    id: lightbar
    name: "$name Light"
    output: light_output
    effects:
      - pulse:
      - strobe:
      - flicker:

binary_sensor:
  - platform: remote_receiver
    id: brightness_up
    internal: true
    pioneer: 
      rc_code_1: 0x09
    on_press: 
      - light.dim_relative:
          id: lightbar
          relative_brightness: 10%

  - platform: remote_receiver
    id: brightness_down
    internal: true
    pioneer: 
      rc_code_1: 0x1D
    on_press: 
      - light.dim_relative:
          id: lightbar
          relative_brightness: -10%

  - platform: remote_receiver
    id: turn_off
    internal: true
    pioneer: 
      rc_code_1: 0x1F
    on_press: 
      - light.turn_off: lightbar

  - platform: remote_receiver
    id: turn_on
    internal: true
    pioneer: 
      rc_code_1: 0x0D
    on_press: 
      - light.turn_on:
          id: lightbar
          effect: none

  - platform: remote_receiver
    id: effect_flicker
    internal: true
    pioneer: 
      rc_code_1: 0x4D
    on_press: 
      - light.turn_on:
          id: lightbar
          effect: flicker

  - platform: remote_receiver
    id: effect_strobe
    internal: true
    pioneer: 
      rc_code_1: 0x00
    on_press: 
      - light.turn_on:
          id: lightbar
          effect: strobe

  - platform: remote_receiver
    id: effect_pulse
    internal: true
    pioneer: 
      rc_code_1: 0x1A
    on_press: 
      - light.turn_on:
          id: lightbar
          effect: pulse

remote_receiver:
  pin:
    number: $pin_remote_receiver
    inverted: true
    mode:
      input: true
      pullup: true