substitutions:
  name: bedroom2-ccfl
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [devices/aubess_single_gang_switch.yaml]
    refresh: 10 min

libretuya:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

