substitutions:
  name: climate-control
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_status_led: GPIO04
  pin_i2c_sda: GPIO12
  pin_i2c_scl: GPIO02
  pin_switch: GPIO13
  pin_remote_receiver: GPIO05
  pin_remote_transmitter: GPIO14
  bmp280_address: "0x76"

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [base.yaml, sensors/bmp280.yaml]
    refresh: 10 min

esp8266:
    board: esp8285

status_led:
  pin:
    number: $pin_status_led

i2c:
  sda: $pin_i2c_sda
  scl: $pin_i2c_scl
  scan: true

binary_sensor:
  - platform: gpio
    pin: 
      number: $pin_switch
      inverted: true
    name: "$name Switch"
    on_release:
      then:
        - button.press: restart_button
 
remote_transmitter:
  id: transmitter
  pin: $pin_remote_transmitter
  carrier_duty_percent: 50%

remote_receiver:
  - id: receiver
    pin:
      number: $pin_remote_receiver 
      inverted: true
    tolerance: 55%

climate:
  - platform: climate_ir_lg
    name: "$name Air Conditioner"
    supports_cool: true
    supports_heat: true
    receiver_id : receiver
    transmitter_id: transmitter
    sensor: sensor_temperature
    visual:
      min_temperature: 18 °C
      max_temperature: 30 °C
      temperature_step: 1 °C