substitutions:
  name: orno-pulse-counter
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_pulse_counter: GPIO03
  pin_status_led: GPIO02
  pin_doorbell: GPIO00

globals:
  - id: total
    type: float
    restore_value: True
    initial_value: "0"

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [base.yaml, status/light.yaml]
    refresh: 10 min

esp8266:
  board: esp12e

logger:
  baud_rate: 0

esphome:
  on_boot: 
    then:
      - pulse_meter.set_total_pulses:
          id: pulse_meter_id
          value: !lambda "return id(total) * 1000;"

preferences:
  flash_write_interval: 5min

api: 
  services: 
    - service: set_total
      variables:
        total: float
      then:
        - pulse_meter.set_total_pulses:
            id: pulse_meter_id
            value: !lambda "return total * 1000;"
        - globals.set: 
            id: total
            value: !lambda return total;

sensor:
  - platform: pulse_meter
    id: pulse_meter_id
    pin: $pin_pulse_counter
    unit_of_measurement: 'kW'
    name: "$name Usage"
    state_class: measurement
    device_class: energy
    internal_filter: 100ms
    accuracy_decimals: 3
    filters:
      - multiply: 0.06
    total:
      name: "$name Total"
      unit_of_measurement: "kWh"
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
      on_value: 
        then:
          - globals.set: 
              id: total
              value: !lambda return x;
          - light.turn_on: statusled
          - delay: 200 ms
          - light.turn_off: statusled
      
binary_sensor:
  - platform: gpio
    pin: 
      number: $pin_doorbell
      inverted: true
    name: $name Doorbell