substitutions:
  name: smartplug
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_button: GPIO13
  pin_status_led: GPIO03
  pin_relay: GPIO12
  pin_hlw8012_sel: GPIO01
  pin_hlw8012_cf: GPIO04
  pin_hlw8012_cf1: GPIO05
  hlw8012_voltage_divider: "2005"
  hlw8012_current_resistor: "0.00088"

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [devices/ledvance_plug.yaml]
    refresh: 10 min

esp8266:
  board: esp8285

    