substitutions:
  name: smartplug-tuya
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_button: GPIO6
  pin_status_led: GPIO10
  pin_relay: GPIO24 
  pin_hlw8012_sel: GPIO22
  pin_hlw8012_cf: GPIO7
  pin_hlw8012_cf1: GPIO8
  hlw8012_voltage_divider: "2005"
  hlw8012_current_resistor: "0.00088"

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [devices/ledvance_plug.yaml]
    refresh: 10 min

libretuya:
  board: wb2s
  framework:
    version: dev