substitutions:
  name: 00-base-project
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # pin_status_led: GPIO02

packages:
  base: github://catalin2402/esphome-base/packages/base.yaml
  # status_led: github://catalin2402/esphome-base/packages/status_led.yaml
  # status_light: github://catalin2402/esphome-base/packages/status_light.yaml
  # camera: github://catalin2402/esphome-base/packages/camera.yaml
esp8266:
  board: esp12e
