---
packages:
  wifi: !include wifi.yaml
  ota: !include ota.yaml
  captive_portal: !include captive_portal.yaml
  logger: !include logger.yaml
  api: !include api.yaml
  web_server: !include web_server.yaml
  button_restart: !include button_restart.yaml
  button_safe_mode: !include button_safe_mode.yaml
  sensor_uptime: !include sensor_uptime.yaml
  sensor_wifi_info: !include sensor_wifi_info.yaml
