---
substitutions:
  name: REPLACEME
  friendly_name: REPLACEME
  wifi_password: REPLACEME
  
esphome:
  name: $name
  friendly_name: $friendly_name

logger:

ota:

wifi:
  ap:
    ssid: $friendly_name Hotspot
    password: $wifi_password


captive_portal:

api:

web_server:
  local: true

button:
  - platform: restart
    id: restart_button
    name: Restart

  - platform: safe_mode
    id: safe_mode_button
    name: Safe Mode
   
time:
  - platform: homeassistant
    id: time_ha
    on_time_sync:
      if:
        condition:
          lambda: return isnan(id(last_restart).state);
        then:
          sensor.template.publish:
            id: last_restart
            state: !lambda return id(time_ha).now().timestamp;

sensor:
  - platform: template
    name: Last Restart
    entity_category: diagnostic
    id: last_restart
    icon: mdi:clock-start
    device_class: timestamp
    update_interval: never

text_sensor: 
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: IP Address