substitutions:
  name: base-8266
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  base: 
    url: https://github.com/catalin2402/esphome-base
    files: [ base.yaml ]
    refresh: 1 min

esphome:
  name: $name
  
esp8266:
  board: esp01_1m
