---
substitutions:
  name: REPLACEME
  wifi_password: REPLACEME
  
esphome:
  name: $name

logger:
  baud_rate: 0
  logs:
    component: ERROR
    
ota:
  platform: esphome
  safe_mode: true

safe_mode:

wifi:
  ap:
    ssid: $name Hotspot
    password: $wifi_password

captive_portal:

api:

web_server:
  local: true

button:
  - platform: restart
    id: restart_button
    name: $name Restart

  - platform: safe_mode
    id: safe_mode_button
    name: $name Safe Mode
    
sensor:
  - platform: uptime
    name: $name Uptime
    
text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: $name IP Address
