---
substitutions:
  name: REPLACEME
  wifi_ssid: REPLACEME
  wifi_password: REPLACEME

esphome:
  name: $name

logger:
  baud_rate: 0
  logs:
    component: ERROR

ota:
  platform: esphome

safe_mode:

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  ap:
    ssid: $name Hotspot
    password: $wifi_password

captive_portal:

api:

web_server:
  local: false
  version: 3

button:
  - platform: restart
    id: restart_button
    icon: mdi:restart
    name: $name Restart

  - platform: safe_mode
    id: safe_mode_button
    icon: mdi:restart-alert
    name: $name Safe Mode

sensor:
  - platform: uptime
    name: $name Uptime

text_sensor: 
  - platform: wifi_info
    ip_address:
      id: ip_address
      icon: mdi:ip-network
      name: $name IP Address
