---
sensor:
  - platform: hlw8012
    model: HLW8012
    sel_pin: $pin_hlw8012_sel
    cf_pin: $pin_hlw8012_cf
    cf1_pin: $pin_hlw8012_cf1
    voltage_divider: $hlw8012_voltage_divider
    current_resistor: $hlw8012_current_resistor
    initial_mode: VOLTAGE
    change_mode_every: 4294967295
    update_interval: 30s
    power:
      name: "$name Power"
      unit_of_measurement: W
      id: "power"
      on_value:
        - component.update: current
    voltage:
      name: "$name Voltage"
      unit_of_measurement: V
      id: voltage

  - platform: total_daily_energy
    name: "$name Energy"
    power_id: "power"
    filters:
        - multiply: 0.001
    unit_of_measurement: kWh 

  - platform: template
    id: current
    name: "$name Current"
    lambda: !lambda 'return id(power).state / id(voltage).state;'
    unit_of_measurement: A
    accuracy_decimals: 3
    update_interval: never