---
sensor:
  - platform: dht
    pin: $pin_temperature_sensor
    temperature:
      id: sensor_temperature
      name: $name Temperature
    humidity:
      id: sensor_humidity
      name: $name Humidity