substitutions:
  name: plug
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_button: GPIO6
  pin_status_led: GPIO10
  pin_relay: GPIO24 
  pin_hlw_sel: GPIO26
  pin_hlw_cf: GPIO7
  pin_hlw_cf1: GPIO8

globals:
  - id: watts
    type: float
    restore_value: no
    initial_value: '0'

packages:
  base: github://catalin2402/esphome-base/packages/base.yaml
  status_light: github://catalin2402/esphome-base/packages/status_light.yaml

libretuya:
  board: wb2s
  framework:
    version: dev

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: $pin_button
      inverted: true
    name: "$name Power Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "$name plug"
    pin: $pin_relay
    id: relay
    on_turn_on:
      - light.turn_on: statusled
    on_turn_off:
      - light.turn_off: statusled

time:
  - platform: homeassistant
    id: my_time

sensor:
  - platform: hlw8012
    model: HLW8012
    sel_pin: $pin_hlw_sel
    cf_pin: $pin_hlw_cf
    cf1_pin: $pin_hlw_cf1
    voltage_divider: 2005
    current_resistor: 0.00088
    initial_mode: VOLTAGE
    change_mode_every: 4294967295
    update_interval: 5s
    power:
      name: "$name Wattage"
      unit_of_measurement: W
      id: "wattage"
      on_value:
        - lambda: |-
            id(watts) = x;
    voltage:
      name: "$name Voltage"
      unit_of_measurement: V
      id: voltage
      on_value:
      - sensor.template.publish:
          id: current
          state: !lambda 'return id(watts) / x;'

  - platform: total_daily_energy
    name: "$name Energy"
    power_id: "wattage"
    filters:
        - multiply: 0.001
    unit_of_measurement: kWh 

  - platform: template
    id: current
    name: "$name Current"
    unit_of_measurement: A
    accuracy_decimals: 2
    update_interval: 5s