---
substitutions:
  bme280_address: REPLACEME

sensor:
  - platform: bme280_i2c
    address: $bme280_address
    temperature:
      id: sensor_temperature
      name: $name Temperature
      icon: mdi:thermometer
    pressure:
      id: sensor_pressure
      name: $name Pressure
      icon: mdi:gauge
    humidity:
      id: sensor_humidity
      name: $name Humidity
      icon: mdi:water-percent
