---
substitutions:
  bmp280_address: REPLACEME
  
sensor:
  - platform: bmp280_i2c
    address: $bmp280_address
    temperature:
      id: sensor_temperature
      name: $name Temperature
      icon: mdi:thermometer
    pressure:
      id: sensor_pressure
      name: $name Pressure
      icon: mdi:gauge
