---
sensor:
  - platform: bmp280
    address: $bmp280_address
    temperature:
      id: sensor_temperature
      name: $name Temperature
    pressure:
      id: sensor_pressure
      name: $name Pressure