---
substitutions:
  pin_dallas: REPLACEME
  dallas_address: REPLACEME
  
dallas:
  - pin:
      number: $pin_dallas
      mode:
        input: true
        pullup: true

sensor:
  - platform: dallas
    address: $dallas_address
    id: sensor_temperature
    name: $name Temperature
    icon: mdi:thermometer
