---
substitutions:
  pin_dallas: REPLACEME
  dallas_address: REPLACEME
  
one_wire:
  - pin:
      number: $pin_dallas
      mode: INPUT_PULLUP

sensor:
  - platform: dallas_temp
    address: $dallas_address
    id: sensor_temperature
    name: $name Temperature
    icon: mdi:thermometer
