---
substitutions:
  pin_dht: REPLACEME

sensor:
  - platform: dht
    pin: $pin_dht
    temperature:
      id: sensor_temperature
      name: $name Temperature
    humidity:
      id: sensor_humidity
      name: $name Humidity