---
sensor:
  - platform: htu21d
    temperature:
      id: sensor_temperature
      name: $name Temperature
      icon: mdi:thermometer
    humidity:
      id: sensor_humidity
      name: $name Humidity
      icon: mdi:water-percent
