---
substitutions:
  pin_relay_1: GPIO8
  pin_relay_2: GPIO7
  pin_status_led: GPIO6
  pin_internal_switch: GPIO10
  pin_external_switch_1: GPIO24
  pin_external_switch_2: GPIO26

packages:
  base: !include ../base.yaml
  status_light: !include ../status/light.yaml

switch:
  - platform: gpio
    name: $name Switch 1
    id: relay_1
    pin: $pin_relay_1
    icon: mdi:light-switch
    on_turn_on:
      light.turn_on: statusled
    on_turn_off:
      light.turn_off: statusled

  - platform: gpio
    name: $name Switch 2
    id: relay_2
    pin: $pin_relay_2
    icon: mdi:light-switch
    on_turn_on:
      light.turn_on: statusled
    on_turn_off:
      light.turn_off: statusled

binary_sensor:
  - platform: gpio
    use_interrupt: false
    id: internal_switch
    pin:
      inverted: true
      number: $pin_internal_switch
      mode: INPUT_PULLUP
    on_double_click:
      button.press: restart_button

  - platform: gpio
    use_interrupt: false
    id: external_switch_1
    pin:
      inverted: true
      number: $pin_external_switch_1
      mode: INPUT_PULLUP
    filters:
      delayed_on_off: 100ms
    on_press:
      switch.turn_on: relay_1
    on_release:
      switch.turn_off: relay_1

  - platform: gpio
    use_interrupt: false
    id: external_switch_2
    pin:
      inverted: true
      number: $pin_external_switch_2
      mode: INPUT_PULLUP
    filters:
      delayed_on_off: 100ms
    on_press:
      switch.turn_on: relay_2
    on_release:
      switch.turn_off: relay_2
