---
substitutions:
  pin_status_led: GPIO6
  pin_relay: GPIO15
  pin_internal_switch: GPIO8
  pin_external_switch: GPIO14

packages:
  base: !include ../base.yaml
  status_light: !include ../status/light.yaml

switch:
  - platform: gpio
    name: $name Switch
    id: relay
    pin: $pin_relay
    icon: mdi:light-switch
    on_turn_on:
      light.turn_on: statusled
    on_turn_off:
      light.turn_off: statusled

binary_sensor:
  - platform: gpio
    id: internal_switch
    pin:
      inverted: true
      number: $pin_internal_switch
      mode: INPUT_PULLUP
    on_double_click:
      button.press: restart_button
    on_click:
      switch.toggle: relay

  - platform: gpio
    id: external_switch
    pin:
      inverted: true
      number: $pin_external_switch
      mode: INPUT_PULLUP
    filters:
      delayed_on_off: 100ms
    on_press:
      switch.turn_on: relay
    on_release:
      switch.turn_off: relay
