---
packages:
  base: !include ../base.yaml
  status_light: !include ../status/light.yaml
  time_homeassistant: !include ../time/ha.yaml
  hlw8012: !include ../sensors/hlw8012.yaml
  
logger:
  baud_rate: 0

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: $pin_button
      inverted: true
    name: "$name Power Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "$name smartplug"
    pin: $pin_relay
    id: relay
    on_turn_on:
      - light.turn_on: statusled
    on_turn_off:
      - light.turn_off: statusled
