---
packages:
  base: !include ../base.yaml
  status_light: !include ../status/light.yaml
  hlw8012: !include ../sensors/hlw8012.yaml

binary_sensor:
  - platform: gpio
    internal: true
    id: internal_button
    pin:
      number: $pin_button
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: $name Socket
    pin: $pin_relay
    id: relay
    on_turn_on:
      - light.turn_on: statusled
    on_turn_off:
      - light.turn_off: statusled
