substitutions:
  name: bulb
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_sm2135_data: GPIO24
  pin_sm2135_clk: GPIO26

packages:
  base: github://catalin2402/esphome-base/packages/base.yaml

external_components:
  - source: github://pr#3850
    components: [ sm2135 ]

libretuya:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev

sm2135:
  data_pin: $pin_sm2135_data 
  clock_pin: $pin_sm2135_clk
  cw_current: 15mA
  rgb_current: 20mA

output:
  - platform: sm2135
    id: output_blue
    channel: 2
  - platform: sm2135
    id: output_red
    channel: 0
  - platform: sm2135
    id: output_green
    channel: 1
  - platform: sm2135
    id: output_coldwhite
    channel: 3
  - platform: sm2135
    id: output_warmwhite
    channel: 4

light:
  - platform: rgbww
    name: "$name Light"
    red: output_red 
    green: output_green 
    blue: output_blue 
    cold_white: output_coldwhite 
    warm_white: output_warmwhite 
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    color_interlock: true
    effects:
      - pulse:
      - random:
      - strobe:
      - flicker: