---
substitutions:
  key01_code: "0xF609"
  key02_code: "0xE21D"
  key03_code: "0xE01F"
  key04_code: "0xF20D"
  key05_code: "0xE619"
  key06_code: "0xE41B"
  key07_code: "0xEE11"
  key08_code: "0xEA15"
  key09_code: "0xE817"
  key10_code: "0xED12"
  key11_code: "0xE916"
  key12_code: "0xB24D"
  key13_code: "0xBF40"
  key14_code: "0xB34C"
  key15_code: "0xFB04"
  key16_code: "0xFF00"
  key17_code: "0xF50A"
  key18_code: "0xE11E"
  key19_code: "0xF10E"
  key20_code: "0xE51A"
  key21_code: "0xE31C"
  key22_code: "0xEB14"
  key23_code: "0xF00F"
  key24_code: "0xF30C"

script:
  id: remote_process
  mode: single
  parameters:
    command: int
  then:
    - if:
        condition:
          - lambda: return command == $key01_code;
        then:
          - light.dim_relative:
              id: remote_light
              relative_brightness: 10%

    - if:
        condition:
          - lambda: return command === $key02_code;
        then:
          - light.dim_relative:
              id: remote_light
              relative_brightness: -10%

    - if:
        condition:
          - lambda: return command == $key03_code;
        then:
          - lambda: |-
              auto call = id(remote_light).make_call();
              if (id(remote_light).remote_values.get_color_mode() == ColorMode::RGB) {
                call.set_color_mode(ColorMode::COLD_WARM_WHITE);
              } else {
                call.set_color_mode(ColorMode::RGB);
              }
              call.perform();

    - if:
        condition:
          - lambda: return command == $key04_code;
        then:
          - light.toggle: remote_light

    - if:
        condition:
          - lambda: return command == $key05_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB              
              red: 1.0
              green: 0.0
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key06_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB                            
              red: 0.0
              green: 1.0
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key07_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB                              
              red: 0.0
              green: 0.0
              blue: 1.0

    - if:
        condition:
          - lambda: return command == $key08_code;
        then:
          - light.control:
              id: remote_light
              color_mode: COLD_WARM_WHITE                    
              color_temperature: 2700 K

    - if:
        condition:
          - lambda: return command == $key09_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB                   
              red: 1.0
              green: 0.47
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key10_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 0.0
              green: 1.0
              blue: 0.47

    - if:
        condition:
          - lambda: return command == $key11_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 0.0
              green: 0.62
              blue: 1.0

    - if:
        condition:
          - lambda: return command == $key12_code;
        then:
          - light.control:
              id: remote_light
              color_mode: COLD_WARM_WHITE    
              color_temperature: 6000 K

    - if:
        condition:
          - lambda: return command == $key13_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 1.0
              green: 0.62
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key14_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 0.0
              green: 1
              blue: 0.62

    - if:
        condition:
          - lambda: return command == $key15_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 0.66
              green: 0.0
              blue: 1.0

    - if:
        condition:
          - lambda: return command == $key16_code;
        then:
          - light.control:
              id: remote_light
              color_mode: COLD_WARM_WHITE    
              color_temperature: !lambda return id(remote_light).remote_values.get_color_temperature() - 5.0f;

    - if:
        condition:
          - lambda: return command == $key17_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 1.0
              green: 0.78
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key18_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 0.0
              green: 1.0
              blue: 0.86

    - if:
        condition:
          - lambda: return command == $key19_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 1.0
              green: 0.0
              blue: 0.86

    - if:
        condition:
          - lambda: return command == $key20_code;
        then:
          - light.control:
              id: remote_light
              color_mode: COLD_WARM_WHITE    
              color_temperature: !lambda return id(remote_light).remote_values.get_color_temperature() + 5.0f;

    - if:
        condition:
          - lambda: return command == $key21_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 1.0
              green: 1.0
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key22_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 0.0
              green: 0.78
              blue: 1.0

    - if:
        condition:
          - lambda: return command == $key23_code;
        then:
          - light.control:
              id: remote_light
              color_mode: RGB
              red: 1.0
              green: 0.0
              blue: 0.62

    - if:
        condition:
          - lambda: return command == $key24_code;
        then:
          - lambda: |-
              auto call = id(remote_light).make_call();
              call.set_effect("Fade 7");
              call.perform();

light:
  - platform: rgbww
    id: remote_light
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
    effects:
      - pulse:
      - strobe:
      - flicker:
      - random:
      - <<: !include { file: ../light-effects/jump-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/jump-7.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-7.yaml, vars: { id: remote_light } }           
