---
substitutions:
  key01_code: "0xF609"
  key02_code: "0xE21D"
  key03_code: "0xE01F"
  key04_code: "0xF20D"
  key05_code: "0xE619"
  key06_code: "0xE41B"
  key07_code: "0xEE11"
  key08_code: "0xEA15"
  key09_code: "0xE817"
  key10_code: "0xED12"
  key11_code: "0xE916"
  key12_code: "0xB24D"
  key13_code: "0xBF40"
  key14_code: "0xB34C"
  key15_code: "0xFB04"
  key16_code: "0xFF00"
  key17_code: "0xF50A"
  key18_code: "0xE11E"
  key19_code: "0xF10E"
  key20_code: "0xE51A"
  key21_code: "0xE31C"
  key22_code: "0xEB14"
  key23_code: "0xF00F"
  key24_code: "0xF30C"

light:
  - platform: rgbww
    id: remote_light
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
    effects:
      - pulse:
      - strobe:
      - flicker:
      - random:
      - <<: !include { file: ../light-effects/jump-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/jump-7.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-7.yaml, vars: { id: remote_light } }           

script:
  id: remote_process
  mode: single
  parameters:
    command: int
  then:
    lambda: |-
      auto call = id(remote_light).make_call();
      auto effect = id(remote_light).get_effect_name();
      auto color_mode = id(remote_light).remote_values.get_color_mode();
      float brightness = id(remote_light).remote_values.get_brightness();
      float color_temperature = id(remote_light).remote_values.get_color_temperature();
      float min_mireds = id(remote_light).get_traits().get_min_mireds();
      float max_mireds = id(remote_light).get_traits().get_max_mireds();

      switch (command) {
        case $key01_code:
          call.set_brightness(clamp(brightness + 0.1f, 0.0f, 1.0f));
          break;

        case $key02_code:
          call.set_brightness(clamp(brightness - 0.1f, 0.1f, 1.0f));
          break;

        case $key03_code:
          call.set_color_mode((color_mode == ColorMode::RGB) ? ColorMode::COLD_WARM_WHITE : ColorMode::RGB);
          break;

        case $key04_code:
          call = id(remote_light).toggle();
          break;

        case $key05_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 0.0f, 0.0f);
          break;

        case $key06_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 1.0f, 0.0f);
          break;

        case $key07_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 0.0f, 1.0f);
          break;

        case $key08_code:
          call.set_color_mode(ColorMode::COLD_WARM_WHITE);
          call.set_color_temperature(min_mireds);
          break;

        case $key09_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 0.47f, 0.0f);
          break;

        case $key10_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 1.0f, 0.47f);
          break;

        case $key11_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 0.62f, 1.0f);
          break;   

        case $key12_code:
          call.set_color_mode(ColorMode::COLD_WARM_WHITE);
          call.set_color_temperature(max_mireds);
          break;

        case $key13_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 0.62f, 0.0f);
          break;

        case $key14_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 1.0f, 0.62f);
          break;

        case $key15_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.66f, 0.0f, 1.0f);
          break;  

        case $key16_code:
          call.set_color_mode(ColorMode::COLD_WARM_WHITE);
          call.set_color_temperature(clamp(color_temperature - 20.0f, min_mireds, max_mireds));
          break;

        case $key17_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 0.78f, 0.0f);
          break;

        case $key18_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 1.0f, 0.86f);
          break;

        case $key19_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 0.0f, 0.86f);
          break;  

        case $key20_code:
          call.set_color_mode(ColorMode::COLD_WARM_WHITE);
          call.set_color_temperature(clamp(color_temperature + 20.0f, min_mireds, max_mireds));
          break;

        case $key21_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 1.0f, 0.0f);
          break;

        case $key22_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(0.0f, 0.78f, 1.0f);
          break;

        case $key23_code:
          call.set_color_mode(ColorMode::RGB);
          call.set_rgb(1.0f, 0.0f, 0.62f);
          break;  

        case $key24_code:
          call.set_effect((effect == "Fade 7")? "None" : "Fade 7");
          break;

      }

      call.perform();