---
substitutions:
  key01_code: "0x"
  key02_code: "0x"
  key03_code: "0x"
  key04_code: "0x"
  key05_code: "0x"
  key06_code: "0x"
  key07_code: "0x"
  key08_code: "0x"
  key09_code: "0x"
  key10_code: "0x"
  key11_code: "0x"
  key12_code: "0x"
  key13_code: "0x"
  key14_code: "0x"
  key15_code: "0x"
  key16_code: "0x"
  key17_code: "0x"
  key18_code: "0x"
  key19_code: "0x"
  key20_code: "0x"
  key21_code: "0x"
  key22_code: "0x"
  key23_code: "0x"
  key24_code: "0x"
  
script:
  id: remote_process
  mode: single
  parameters:
    command: int
  then:
    - if:
        condition:
          - lambda: return command == $key01_code;
        then:
          - light.dim_relative:
              id: remote_light
              relative_brightness: 10%

    - if:
        condition:
          - lambda: return command == $key02_code;
        then:
          - light.dim_relative:
              id: remote_light
              relative_brightness: -10%

    - if:
        condition:
          - lambda: return command == $key03_code;
        then:
          - light.turn_off: remote_light

    - if:
        condition:
          - lambda: return command == $key04_code;
        then:
          - light.turn_on: remote_light

    - if:
        condition:
          - lambda: return command == $key05_code;
        then:
          - light.control:
              id: remote_light
              red: 1.0
              green: 0.0
              blue: 0.0

    - if:
        condition:
          - lambda: return command == $key06_code;
        then:
          - light.control:
              id: remote_light
              red: 0.0
              green: 1.0
              blue: 0.0

    - if:
          condition:
            - lambda: return command == $key07_code;
          then:
            - light.control:
                id: remote_light
                red: 0.0
                green: 0.0
                blue: 1.0

    - if:
          condition:
            - lambda: return command == $key08_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 1.0
                blue: 1.0

    - if:
          condition:
            - lambda: return command == $key09_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 0.47
                blue: 0.0

    - if:
          condition:
            - lambda: return command == $key10_code;
          then:
            - light.control:
                id: remote_light
                red: 0.0
                green: 1.0
                blue: 0.47

    - if:
          condition:
            - lambda: return command == $key11_code;
          then:
            - light.control:
                id: remote_light
                red: 0.0
                green: 0.62
                blue: 1.0

    - if:
          condition:
            - lambda: return command == $key12_code;
          then:
            - lambda: |-
                auto call = id(remote_light).make_call();
                call.set_effect("Pulse");
                call.perform();

    - if:
          condition:
            - lambda: return command == $key13_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 0.62
                blue: 0.0

    - if:
          condition:
            - lambda: return command == $key14_code;
          then:
            - light.control:
                id: remote_light
                red: 0.0
                green: 1
                blue: 0.62

    - if:
          condition:
            - lambda: return command == $key15_code;
          then:
            - light.control:
                id: remote_light
                red: 0.66
                green: 0.0
                blue: 1.0

    - if:
          condition:
            - lambda: return command == $key16_code;
          then:
            - lambda: |-
                auto call = id(remote_light).make_call();
                call.set_effect("Strobe");
                call.perform();

    - if:
          condition:
            - lambda: return command == $key17_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 0.78
                blue: 0.0

    - if:
          condition:
            - lambda: return command == $key18_code;
          then:
            - light.control:
                id: remote_light
                red: 0.0
                green: 1.0
                blue: 0.86

    - if:
          condition:
            - lambda: return command == $key19_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 0.0
                blue: 0.86

    - if:
          condition:
            - lambda: return command == $key20_code;
          then:
            - lambda: |-
                auto call = id(remote_light).make_call();
                call.set_effect("Fade 7");
                call.perform();

    - if:
          condition:
            - lambda: return command == $key21_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 1.0
                blue: 0.0

    - if:
          condition:
            - lambda: return command == $key22_code;
          then:
            - light.control:
                id: remote_light
                red: 0.0
                green: 0.78
                blue: 1.0

    - if:
          condition:
            - lambda: return command == $key23_code;
          then:
            - light.control:
                id: remote_light
                red: 1.0
                green: 0.0
                blue: 0.62

    - if:
        condition:
          - lambda: return command == $key24_code;
        then:
          - lambda: |-
              auto call = id(remote_light).make_call();
              call.set_effect("Random");
              call.perform();
light:
  - platform: custom
    id: remote_light
    effects:
      - pulse:
      - strobe:
      - flicker:
      - random:
      - <<: !include { file: ../light-effects/jump-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/jump-7.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-7.yaml, vars: { id: remote_light } }           