---
substitutions:
  key01_code: "0xFA05"
  key02_code: "0xFB04"
  key03_code: "0xF906"
  key04_code: "0xF807"
  key05_code: "0xF609"
  key06_code: "0xF708"
  key07_code: "0xF50A"
  key08_code: "0xF40B"
  key09_code: "0xF20D"
  key10_code: "0xF30C"
  key11_code: "0xF10E"
  key12_code: "0xF00F"
  key13_code: "0xEA15"
  key14_code: "0xEB14"
  key15_code: "0xE916"
  key16_code: "0xE817"
  key17_code: "0xE619"
  key18_code: "0xE718"
  key19_code: "0xE51A"
  key20_code: "0xE41B"
  key21_code: "0xEE11"
  key22_code: "0xEF10"
  key23_code: "0xED12"
  key24_code: "0xEC13"
  
light:
  - platform: custom
    id: remote_light
    effects:
      - pulse:
      - strobe:
      - flicker:
      - random:
      - <<: !include { file: ../light-effects/jump-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/jump-7.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-3.yaml, vars: { id: remote_light } }
      - <<: !include { file: ../light-effects/fade-7.yaml, vars: { id: remote_light } }           

script:
  id: remote_process
  mode: single
  parameters:
    command: int
  then:
    lambda: |-
      auto call = id(remote_light).make_call();
      auto effect = id(remote_light).get_effect_name();
      float brightness = id(remote_light).remote_values.get_brightness();

      switch (command) {
        case $key01_code:
          call.set_brightness(clamp(brightness + 0.1f, 0.0f, 1.0f));
          break;

        case $key02_code:
          call.set_brightness(clamp(brightness - 0.1f, 0.1f, 1.0f));
          break;

        case $key03_code:
          call = id(remote_light).turn_off();
          break;

        case $key04_code:
          call = id(remote_light).turn_on();
          break;

        case $key05_code:
          call.set_rgb(1.0f, 0.0f, 0.0f);
          break;

        case $key06_code:
          call.set_rgb(0.0f, 1.0f, 0.0f);
          break;

        case $key07_code:
          call.set_rgb(0.0f, 0.0f, 1.0f);
          break;

        case $key08_code:
          call.set_rgb(1.0f, 1.0f, 1.0f);
          break;

        case $key09_code:
          call.set_rgb(1.0f, 0.47f, 0.0f);
          break;

        case $key10_code:
          call.set_rgb(0.0f, 1.0f, 0.47f);
          break;

        case $key11_code:
          call.set_rgb(0.0f, 0.62f, 1.0f);
          break;   

        case $key12_code:
          call.set_effect((effect == "Pulse") ? "None" : "Pulse");
          break;

        case $key13_code:
          call.set_rgb(1.0f, 0.62f, 0.0f);
          break;

        case $key14_code:
          call.set_rgb(0.0f, 1.0f, 0.62f);
          break;

        case $key15_code:
          call.set_rgb(0.66f, 0.0f, 1.0f);
          break;  

        case $key16_code:
          call.set_effect((effect == "Strobe") ? "None" : "Strobe");
          break;

        case $key17_code:
          call.set_rgb(1.0f, 0.78f, 0.0f);
          break;

        case $key18_code:
          call.set_rgb(0.0f, 1.0f, 0.86f);
          break;

        case $key19_code:
          call.set_rgb(1.0f, 0.0f, 0.86f);
          break;  

        case $key20_code:
          call.set_effect((effect == "Fade 7") ? "None" : "Fade 7");
          break;

        case $key21_code:
          call.set_rgb(1.0f, 1.0f, 0.0f);
          break;

        case $key22_code:
          call.set_rgb(0.0f, 0.78f, 1.0f);
          break;

        case $key23_code:
          call.set_rgb(1.0f, 0.0f, 0.62f);
          break;  

        case $key24_code:
          call.set_effect((effect == "Random") ? "None" : "Random");
          break;

      }
      
      call.perform();
