---
substitutions:
  pin_servo_1: REPLACEME
  pin_servo_2: REPLACEME
  default_servo_pan: "0"
  default_servo_tilt: "0"

esphome:
  on_boot: 
    - wait_until:
        condition:
          api.connected:
    - number.set: 
        id: pan
        value: $default_servo_pan
    - number.set: 
        id: tilt
        value: $default_servo_tilt  

output: 
  - platform: ledc
    id: servo1_output
    pin: $pin_servo_1
    channel: 4
    frequency: 50 Hz

  - platform: ledc
    id: servo2_output
    pin: $pin_servo_2
    channel: 5
    frequency: 50 Hz   

servo:
  - id: servo_1
    output: servo1_output
    auto_detach_time: 1 s

  - id: servo_2
    output: servo2_output
    auto_detach_time: 1 s

number:
  - platform: template
    id: pan
    name: "$name Pan"
    min_value: -100
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      - servo.write:
          id: servo_1
          level: !lambda 'return x / 100.0;'

  - platform: template
    name: "$name Tilt"
    id: tilt
    min_value: -100
    max_value: 100
    optimistic: true
    step: 1
    set_action:
      - servo.write:
          id: servo_2
          level: !lambda 'return x / 100.0;'
