substitutions:
  name: switch
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  pin_status_led: GPIO6
  pin_relay: GPIO15
  pin_internal_switch: GPIO8
  pin_external_switch: GPIO14

packages:
  base: github://catalin2402/esphome-base/packages/base.yaml
  status: github://catalin2402/esphome-base/packages/status_light.yaml

libretuya:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev
    
switch:
  - platform: gpio
    name: "$name Relay"
    id: relay
    pin: $pin_relay
    on_turn_on:
      then:
        - light.turn_on: statusled
    on_turn_off:
      then:
        - light.turn_off: statusled

  - platform: restart
    internal: true
    name: "$name Restart"
    id: restartswitch

binary_sensor:
  - platform: gpio
    internal: true
    id: internal_switch
    pin:
      inverted: true
      number: $pin_internal_switch
      mode:
        input: true
        pullup: true
    on_double_click:
      then:
        - switch.toggle: restartswitch
    on_click:
      then:
        - switch.toggle: relay

  - platform: gpio
    internal: true
    id: external_switch
    pin:
      inverted: true
      number: $pin_external_switch
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on_off: 100ms
    on_press:
      then:
        - switch.turn_on: relay
    on_release:
      then:
        - switch.turn_off: relay