---
esphome:
  name: ${name}

packages:
  wifi: !include wifi.yaml
  ota: !include ota.yaml
  captive_portal: !include captive_portal.yaml
  logger: !include logger.yaml
  api: !include api.yaml
  web_server: !include web_server.yaml
  restart_button: !include buttons/restart_button.yaml
  safe_mode_button: !include buttons/safe_mode_button.yaml
  uptime: !include sensors/uptime.yaml
  wifi_info: !include sensors/wifi_info.yaml
